### ISSUE TITLE
Missing required module 'CLZMA'

### ISSUE THREAD

**Issue by bulusoy** [BlockchainCommons/BCSwiftTor#1]
Hi @wolfmcnally,

first, thank you for this project.

Adding `BCSwiftTor` as Package in Xcode, works as desired.

Using `BCSwiftTor` is not possible at the moment. xcodebuild raises an error: `Missing required module 'CLZMA'`.

I've built `BCSwiftTorBase`, copied the framework to `BCSwiftTor/Frameworks` and ran the test target of `BCCSwiftTor`. Everything worked as expected.

**Comment by wolfmcnally** [comment]
@bulusoy 
Did you make any changes to BCSwiftTorBase, or did you just build it?
What system/processor were you targeting in your attempt to use BCSwiftTor?

**Comment by bulusoy** [comment]
@wolfmcnally I just built it. 

Build environment:
Model Identifier:	MacBookPro11,5
Processor Name:	Quad-Core Intel Core i7
Processor Speed:	2,5 GHz
Number of Processors:	1
Total Number of Cores:	4

**Comment by ChristopherA** [comment]
@bulusoy I'm confused — the error went away? Or it still has the error?

**Comment by wolfmcnally** [comment]
@bulusoy Please open another issue if this persists.
